apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-test-m6i
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cpu-test-m6i
  template:
    metadata:
      labels:
        app: cpu-test-m6i
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: m6i.8xlarge
      containers:
      - name: cpu-performance-test
        image: 932423224465.dkr.ecr.ap-southeast-1.amazonaws.com/cpu-performance-test:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-test-m6i
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: cpu-test-m6i
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-test-m7i
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cpu-test-m7i
  template:
    metadata:
      labels:
        app: cpu-test-m7i
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: m7i.8xlarge
      containers:
      - name: cpu-performance-test
        image: 932423224465.dkr.ecr.ap-southeast-1.amazonaws.com/cpu-performance-test:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-test-m7i
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
  selector:
    app: cpu-test-m7i
