apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-test-r8g
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-test-r8g
  template:
    metadata:
      labels:
        app: cpu-test-r8g
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: r8g.8xlarge
      containers:
      - name: cpu-performance-test
        image: 932423224465.dkr.ecr.ap-southeast-1.amazonaws.com/cpu-performance-test:latest
        env:
        - name: JAVA_OPTS
          value: "-XX:+UseZGC -Xmx64g -Xms64g -XX:+UseNUMA -Xlog:gc*=info:file=/tmp/gc.log:time,uptime,level,tags"
        resources:
          requests:
            memory: "70Gi"
            cpu: "30"
          limits:
            memory: "70Gi"
            cpu: "30"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-test-r8g
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30085
  selector:
    app: cpu-test-r8g